version: "3"

vars:
    PKGS: {sh: GOFLAGS=-mod=vendor go list ./... | grep -vE -e /vendor/ -e /pkg/swagger/}
    
tasks:
    build:
        desc: Build the app
        cmds:
        - go build -o bin/go-rest-api internal/main.go 

    generate:
        desc: generate Go code
        cmds:
        - GOFLAGS=-mod=vendor go generate github.com/scraly/learning-go-by-examples/go-rest-api/internal
        - GOFLAGS=-mod=vendor go generate github.com/scraly/learning-go-by-examples/go-rest-api/pkg/swagger

    swagger.validate:
        desc: Validate swagger
        cmds:
        - swagger validate pkg/swagger/swagger.yml

    swagger.doc:
        desc: Doc for swagger
        cmds:
        - docker run -i yousan/swagger-yaml-to-html < pkg/swagger/swagger.yml > doc/index.html